build:
  image: default-jammy

  nodes:
    analysis:
      environment:
        php:
          version: 8.4
          pecl_extensions:
            - pcov
          ini:
            memory_limit: -1
            pcov.enabled: 1

      project_setup:
        override:
          - composer install --no-interaction --prefer-dist

      tests:
        override:
          - php-scrutinizer-run
          -
            command: vendor/bin/phpunit --coverage-clover=coverage.xml
            coverage:
              file: coverage.xml
              format: clover

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths:
    - src/
  excluded_paths:
    - tests/
    - examples/
    - docs/
