FROM php:8.4-cli

RUN apt-get update && apt-get install -y libzip-dev unzip \
    && pecl install pcov \
    && docker-php-ext-enable pcov \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
